# Generated by Django 6.0.1 on 2026-01-20 12:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
        ('organizations', '0006_alter_membership_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audit',
            options={'ordering': ['-organization_id', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='evidence',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='audit',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization this audit belongs to. Critical for data isolation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='audit',
            name='triggered_by',
            field=models.ForeignKey(blank=True, help_text='The user who initiated this audit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_triggered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evidence',
            name='comment',
            field=models.TextField(blank=True, help_text='Human-readable summary of the finding', null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='raw_data',
            field=models.JSONField(default=dict, help_text='Raw API response or logs proving the result. Contains actual evidence from external systems.'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['organization', 'created_at'], name='audits_audi_organiz_20bf2d_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['organization', 'status'], name='audits_audi_organiz_eccc28_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['audit', 'status'], name='audits_evid_audit_i_5bbb22_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['question', 'status'], name='audits_evid_questio_273f83_idx'),
        ),
    ]
