# Generated by Django 6.0.1 on 2026-01-23 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_alter_audit_options_alter_evidence_options_and_more'),
        ('organizations', '0007_add_billing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-friendly name for this snapshot', max_length=255)),
                ('version', models.PositiveIntegerField(help_text='Incremental version number for this audit')),
                ('data', models.JSONField(help_text='The immutable snapshot data (audit + evidence)')),
                ('checksum', models.CharField(help_text='SHA256 checksum of the data field for integrity', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.ForeignKey(help_text='The source audit this snapshot was created from', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='audits.audit')),
                ('created_by', models.ForeignKey(help_text='User who triggered the snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization isolation', on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='audits_audi_organiz_0754af_idx')],
                'unique_together': {('audit', 'version')},
            },
        ),
    ]
