# Generated by Django 6.0.1 on 2026-01-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_auditsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='score',
            field=models.IntegerField(default=0, help_text='Audit compliance score (0-100)'),
        ),
    ]
