# Generated by Django 6.0.1 on 2026-01-24 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_audit_score'),
        ('organizations', '0007_add_billing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='organization',
            field=models.ForeignKey(default='041d127a-7b3e-4e39-8cec-c7fbb3a7e3d9', help_text='The organization this audit belongs to. Critical for data isolation.', on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='organizations.organization'),
            preserve_default=False,
        ),
    ]
