# Generated by Django 5.2.10 on 2026-01-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0005_alter_audit_organization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evidence',
            unique_together=set(),
        ),
    ]
