# Generated by Django 5.2.10 on 2026-01-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_alter_evidence_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='remediation_steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='audit_proofs/%Y/%m/'),
        ),
    ]
