# Generated by Django 5.2.10 on 2026-01-26 10:38

import apps.audits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_evidence_remediation_steps_evidence_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='score_value',
            field=models.IntegerField(default=0, help_text='Audit compliance score value'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='remediation_status',
            field=models.CharField(default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='evidence',
            name='status_state',
            field=models.CharField(choices=[('OPEN', 'Open'), ('FIXED', 'Fixed'), ('RISK_ACCEPTED', 'Risk Accepted')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=apps.audits.models.evidence_upload_path),
        ),
    ]
