# Generated by Django 5.2.10 on 2026-01-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_evidence_remediation_steps_evidence_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='details',
            field=models.JSONField(default=dict, help_text='Detailed scoring breakdown'),
        ),
        migrations.AddField(
            model_name='audit',
            name='grade',
            field=models.CharField(blank=True, help_text='Letter grade (A, B, C, F)', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='manual_proof',
            field=models.FileField(blank=True, help_text='Upload proof of manual fix (e.g., PDF, Image)', null=True, upload_to='evidence/proofs/'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='risk_acceptance_reason',
            field=models.TextField(blank=True, help_text='Reason for accepting the risk if workflow_status is RISK_ACCEPTED', null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='workflow_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('FIXED', 'Fixed'), ('RISK_ACCEPTED', 'Risk Accepted')], default='OPEN', help_text='Manual workflow status for tracking remediation', max_length=20),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['audit', 'workflow_status'], name='audits_evid_audit_i_86206d_idx'),
        ),
    ]
