# Generated by Django 5.2.10 on 2026-01-27 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_audit_score_value_evidence_remediation_status_and_more'),
        ('organizations', '0009_organization_trial_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAcceptanceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(help_text='The key of the check to skip/waive (e.g. cis_1_1)', max_length=50)),
                ('reason', models.TextField(help_text='Justification for why this risk is accepted')),
                ('date_accepted', models.DateTimeField(auto_now_add=True)),
                ('resource_identifier', models.CharField(blank=True, help_text='Specific resource to waive (e.g. repo name). If empty, waives for entire org?', max_length=255, null=True)),
                ('organization', models.ForeignKey(help_text='Organization this exception applies to', on_delete=django.db.models.deletion.CASCADE, related_name='risk_exceptions', to='organizations.organization')),
                ('user', models.ForeignKey(help_text='User who accepted the risk', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'check_id', 'resource_identifier')},
            },
        ),
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(help_text='Daily Posture Score (0-100)')),
                ('total_fail', models.IntegerField()),
                ('total_pass', models.IntegerField()),
                ('organization', models.ForeignKey(blank=True, help_text='Organization for this history record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_history', to='organizations.organization')),
                ('user', models.ForeignKey(help_text='User associated with this scan metric', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['organization', 'date'], name='audits_scan_organiz_55adc0_idx')],
            },
        ),
    ]
