# Generated by Django 5.2.10 on 2026-01-25 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_audit_details_audit_grade_evidence_manual_proof_and_more'),
        ('organizations', '0010_organization_slack_webhook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='status',
            field=models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('ERROR', 'Error'), ('RISK_ACCEPTED', 'Risk Accepted')], max_length=20),
        ),
        migrations.CreateModel(
            name='SecuritySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('score', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('critical_count', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_snapshots', to='organizations.organization')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['organization', 'date'], name='audits_secu_organiz_8aa755_idx')],
            },
        ),
    ]
