# Generated by Django 5.2.10 on 2026-01-28 07:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0009_riskacceptanceexception_scanhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditsnapshot',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='If True, this snapshot cannot be deleted by retention policies'),
        ),
        migrations.AddField(
            model_name='auditsnapshot',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Generated PDF report for this snapshot', null=True, upload_to='audit_reports/'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('FROZEN', 'Frozen')], default='RUNNING', max_length=20),
        ),
        migrations.CreateModel(
            name='PublicLink',
            fields=[
                ('token', models.CharField(default=uuid.uuid4, editable=False, help_text='Secure random token for public access', max_length=64, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(help_text='The snapshot exposed by this link', on_delete=django.db.models.deletion.CASCADE, related_name='public_links', to='audits.auditsnapshot')),
            ],
        ),
    ]
