# Generated by Django 5.2.10 on 2026-01-28 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0010_auditsnapshot_is_pinned_auditsnapshot_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='status',
            field=models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('ERROR', 'Error'), ('RISK_ACCEPTED', 'Risk Accepted')], max_length=50),
        ),
    ]
