# Generated by Django 5.2.10 on 2026-01-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_verified_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_comped_vip',
            field=models.BooleanField(default=False, help_text='Super Admin Override: Grants full Pro access regardless of Stripe status.'),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_subscription_status',
            field=models.CharField(default='free', help_text='Current Stripe status (active, past_due, canceled, free)', max_length=20),
        ),
    ]
