# Generated by Django 6.0.1 on 2026-01-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationinvite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-joined_at'], 'verbose_name': 'Membership', 'verbose_name_plural': 'Memberships'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['-created_at'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.RemoveIndex(
            model_name='membership',
            name='organizations_membership_user_org_idx',
        ),
        migrations.RenameIndex(
            model_name='membership',
            new_name='organizatio_organiz_e82976_idx',
            old_name='organizations_membership_org_role_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_slug_048085_idx',
            old_name='organizations_organization_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_owner_i_370edd_idx',
            old_name='organizations_organization_owner_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationinvite',
            new_name='organizatio_organiz_34ffed_idx',
            old_name='organizations_invite_org_email_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationinvite',
            new_name='organizatio_status_5a7dd0_idx',
            old_name='organizations_invite_status_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationinvite',
            new_name='organizatio_expires_c4a92f_idx',
            old_name='organizations_invite_expires_idx',
        ),
        migrations.AlterUniqueTogether(
            name='organizationinvite',
            unique_together={('organization', 'email', 'status')},
        ),
    ]
