# Generated by Django 6.0.1 on 2026-01-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_membership_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinvite',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True),
        ),
    ]
