# Generated by Django 6.0.1 on 2026-01-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_membership_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Customer ID for this organization', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Subscription ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_ends_at',
            field=models.DateTimeField(blank=True, help_text='When the subscription expires or ends', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_started_at',
            field=models.DateTimeField(blank=True, help_text='When the subscription became active', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(choices=[('free', 'Free'), ('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled')], db_index=True, default='free', help_text='Current subscription status', max_length=20),
        ),
    ]
