# Generated by Django 5.2.10 on 2026-01-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='trial_start_date',
            field=models.DateTimeField(blank=True, help_text='When the 15-day trial started', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(choices=[('free', 'Free'), ('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('expired', 'Expired'), ('canceled', 'Canceled')], db_index=True, default='free', help_text='Current subscription status', max_length=20),
        ),
    ]
