# Generated by Django 5.2.10 on 2026-01-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_organization_trial_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='slack_webhook_url',
            field=models.URLField(blank=True, help_text='Slack Webhook URL for regression alerts', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro')], db_index=True, default='FREE', help_text='Subscription tier (Free vs Pro)', max_length=20),
        ),
    ]
