# Generated by Django 5.2.10 on 2026-01-24 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0005_alter_audit_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The generated PDF file', upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit', models.OneToOneField(help_text='The audit for which this report was generated', on_delete=django.db.models.deletion.CASCADE, related_name='report', to='audits.audit')),
            ],
        ),
    ]
