# Generated by Django 6.0.1 on 2026-01-15 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub')], max_length=50)),
                ('_access_token', models.TextField(db_column='access_token')),
                ('_refresh_token', models.TextField(blank=True, db_column='refresh_token', null=True)),
                ('identifier', models.CharField(help_text='External ID (e.g. Installation ID)', max_length=255)),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='organizations.organization')),
            ],
            options={
                'unique_together': {('organization', 'provider', 'identifier')},
            },
        ),
    ]
