# Generated by Django 6.0.1 on 2026-01-20 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('organizations', '0006_alter_membership_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integration',
            options={'verbose_name': 'Integration', 'verbose_name_plural': 'Integrations'},
        ),
        migrations.AddField(
            model_name='integration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integration',
            name='name',
            field=models.CharField(blank=True, help_text="Friendly name (e.g., 'Prod GitHub')", max_length=100),
        ),
        migrations.AlterField(
            model_name='integration',
            name='_access_token',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='_refresh_token',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integration',
            name='identifier',
            field=models.CharField(help_text='External ID (e.g. GitHub Organization name or Installation ID)', max_length=255),
        ),
        migrations.AlterField(
            model_name='integration',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict, help_text='Store extra provider data here (scopes, expiry, repo_name, etc)'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('jira', 'Jira')], default='github', max_length=50),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['organization', 'provider'], name='integration_organiz_9ecb77_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['created_by', 'created_at'], name='integration_created_09ace3_idx'),
        ),
    ]
