# Generated by Django 6.0.1 on 2026-01-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_integration_options_integration_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('jira', 'Jira'), ('aws', 'AWS')], default='github', max_length=50),
        ),
    ]
