# Generated by Django 6.0.1 on 2026-01-23 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_alter_integration_provider'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='integration',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Store provider-specific metadata here'),
        ),
        migrations.AddField(
            model_name='integration',
            name='external_id',
            field=models.CharField(default=django.utils.timezone.now, help_text='External ID (e.g. GitHub Organization ID or Repo ID)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integration',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='integration',
            name='name',
            field=models.CharField(blank=True, help_text="Friendly name (e.g., 'Engineering Team's Repo')", max_length=100),
        ),
        migrations.AlterField(
            model_name='integration',
            name='provider',
            field=models.CharField(choices=[('github', 'GitHub')], default='github', max_length=50),
        ),
        migrations.RemoveField(
            model_name='integration',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='meta_data',
        ),
    ]
