# Generated by Django 6.0.1 on 2026-01-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_alter_integration_unique_together_integration_config_and_more'),
        ('organizations', '0007_add_billing_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together={('organization', 'provider', 'external_id')},
        ),
    ]
