# Generated by Django 6.0.1 on 2026-01-24 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_alter_integration_unique_together'),
        ('organizations', '0007_add_billing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='organizations.organization'),
        ),
    ]
